# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/musical-trimmer',
                'doc_host': 'https://tylerweitzman.github.io',
                'git_url': 'https://github.com/tylerweitzman/musical-trimmer',
                'lib_path': 'musical_trimmer'},
  'syms': {'musical_trimmer.core': {'musical_trimmer.core.foo': ('core.html#foo', 'musical_trimmer/core.py')}}}
